export class UIStyleSelector {
  getStyle(category) {
    return this.STYLES[category] || this.STYLES.technology
  }

  STYLES = {
    gaming: {
      colors: { primary: '#E100FF', secondary: '#00FFE5', accent: '#FFD700', background: '#0A0015' },
      typography: { headline: 'Anton', caption: 'Inter', size_headline: 130, size_caption: 52 },
      motion: { default: 'glitch_fast', transition: 'pixel_slide', camera: 'fast_zoom' },
      effects: ['glitch', 'scanlines', 'pixelation', 'rgb_split'],
      audio: { music: 'arcade_cinematic', sfx: '8bit' },
      banner: 'pixel_banner',
      overlay: 'crt_scanlines',
      ticker_style: 'pixel',
      icon: '🎮',
    },
    ai: {
      colors: { primary: '#00E5FF', secondary: '#E10600', accent: '#FFFFFF', background: '#050510' },
      typography: { headline: 'Anton', caption: 'Inter', size_headline: 120, size_caption: 52 },
      motion: { default: 'holographic', transition: 'zoom_blur', camera: 'orbit' },
      effects: ['hologram', 'light_sweep', 'data_particles', 'glow'],
      audio: { music: 'cinematic_tech', sfx: 'digital' },
      banner: 'neon_banner',
      overlay: 'data_grid',
      ticker_style: 'cyber',
      icon: '🤖',
    },
    robotics: {
      colors: { primary: '#FF6B00', secondary: '#00E5FF', accent: '#FFFFFF', background: '#0A0500' },
      typography: { headline: 'Anton', caption: 'Inter', size_headline: 120, size_caption: 52 },
      motion: { default: 'mechanical', transition: 'glitch', camera: 'push_in' },
      effects: ['scanlines', 'mechanical_overlay', 'hud_elements'],
      audio: { music: 'industrial', sfx: 'mechanical' },
      banner: 'tech_banner',
      overlay: 'hud',
      ticker_style: 'tech',
      icon: '⚙️',
    },
    cybersecurity: {
      colors: { primary: '#00FF41', secondary: '#E10600', accent: '#FFFFFF', background: '#000A05' },
      typography: { headline: 'Anton', caption: 'Inter', size_headline: 110, size_caption: 52 },
      motion: { default: 'glitch', transition: 'glitch', camera: 'shake' },
      effects: ['glitch', 'matrix_rain', 'scanlines', 'terminal_overlay'],
      audio: { music: 'cyber_threat', sfx: 'digital_alert' },
      banner: 'threat_banner',
      overlay: 'terminal',
      ticker_style: 'code',
      icon: '🛡️',
    },
    space: {
      colors: { primary: '#FFFFFF', secondary: '#00E5FF', accent: '#FFD700', background: '#000510' },
      typography: { headline: 'Anton', caption: 'Inter', size_headline: 110, size_caption: 52 },
      motion: { default: 'slow_drift', transition: 'light_leak', camera: 'orbit' },
      effects: ['particles', 'starfield', 'light_sweep', 'glow'],
      audio: { music: 'epic_cinematic', sfx: 'whoosh' },
      banner: 'space_banner',
      overlay: 'starfield',
      ticker_style: 'space',
      icon: '🚀',
    },
    sports: {
      colors: { primary: '#FFD700', secondary: '#E10600', accent: '#FFFFFF', background: '#050510' },
      typography: { headline: 'Anton', caption: 'Inter', size_headline: 130, size_caption: 52 },
      motion: { default: 'fast_pan', transition: 'flash', camera: 'action_zoom' },
      effects: ['motion_blur', 'score_overlay', 'flash'],
      audio: { music: 'energetic_stadium', sfx: 'crowd_roar' },
      banner: 'sports_banner',
      overlay: 'scoreboard',
      ticker_style: 'score',
      icon: '🏆',
    },
    politics: {
      colors: { primary: '#E10600', secondary: '#0044FF', accent: '#FFFFFF', background: '#050508' },
      typography: { headline: 'Inter', caption: 'Inter', size_headline: 100, size_caption: 52 },
      motion: { default: 'slow_push', transition: 'fade', camera: 'stable' },
      effects: ['data_panel', 'map_overlay', 'chart'],
      audio: { music: 'professional_news', sfx: 'alert' },
      banner: 'news_banner',
      overlay: 'newsroom',
      ticker_style: 'news',
      icon: '🏛️',
    },
    science: {
      colors: { primary: '#00E5FF', secondary: '#FFFFFF', accent: '#FFD700', background: '#000510' },
      typography: { headline: 'Anton', caption: 'Inter', size_headline: 110, size_caption: 52 },
      motion: { default: 'slow_zoom', transition: 'zoom_blur', camera: 'microscope' },
      effects: ['particles', 'data_visualization', 'glow'],
      audio: { music: 'discovery', sfx: 'whoosh' },
      banner: 'science_banner',
      overlay: 'laboratory',
      ticker_style: 'scientific',
      icon: '🔬',
    },
    biotech: {
      colors: { primary: '#00FF88', secondary: '#00E5FF', accent: '#FFFFFF', background: '#000A05' },
      typography: { headline: 'Anton', caption: 'Inter', size_headline: 110, size_caption: 52 },
      motion: { default: 'slow_zoom', transition: 'zoom_blur', camera: 'micro' },
      effects: ['particles', 'dna_helix', 'glow'],
      audio: { music: 'discovery', sfx: 'whoosh' },
      banner: 'science_banner',
      overlay: 'laboratory',
      ticker_style: 'scientific',
      icon: '🧬',
    },
    programming: {
      colors: { primary: '#00E5FF', secondary: '#FFD700', accent: '#FFFFFF', background: '#050510' },
      typography: { headline: 'Anton', caption: 'Inter', size_headline: 110, size_caption: 52 },
      motion: { default: 'code_scroll', transition: 'glitch', camera: 'push_in' },
      effects: ['code_rain', 'terminal', 'scanlines'],
      audio: { music: 'tech_beats', sfx: 'keyboard' },
      banner: 'tech_banner',
      overlay: 'code_editor',
      ticker_style: 'code',
      icon: '💻',
    },
    quantum: {
      colors: { primary: '#E100FF', secondary: '#00E5FF', accent: '#FFFFFF', background: '#050005' },
      typography: { headline: 'Anton', caption: 'Inter', size_headline: 110, size_caption: 52 },
      motion: { default: 'particle_dance', transition: 'glitch', camera: 'orbit' },
      effects: ['particles', 'glow', 'rgb_split'],
      audio: { music: 'ambient_sci_fi', sfx: 'digital' },
      banner: 'tech_banner',
      overlay: 'quantum_grid',
      ticker_style: 'scientific',
      icon: '⚛️',
    },
    technology: {
      colors: { primary: '#E10600', secondary: '#00E5FF', accent: '#FFFFFF', background: '#050505' },
      typography: { headline: 'Anton', caption: 'Inter', size_headline: 130, size_caption: 52 },
      motion: { default: 'push_in', transition: 'flash', camera: 'zoom' },
      effects: ['glitch', 'scanlines', 'light_sweep', 'particles'],
      audio: { music: 'cinematic_tech', sfx: 'impact' },
      banner: 'breaking_banner',
      overlay: 'tech_grid',
      ticker_style: 'tech',
      icon: '⚡',
    },
    lifestyle: {
      colors: { primary: '#FF6B9D', secondary: '#00E5FF', accent: '#FFD700', background: '#050510' },
      typography: { headline: 'Anton', caption: 'Inter', size_headline: 110, size_caption: 52 },
      motion: { default: 'smooth_pan', transition: 'light_leak', camera: 'dolly' },
      effects: ['glow', 'light_leak', 'bokeh'],
      audio: { music: 'upbeat_modern', sfx: 'whoosh' },
      banner: 'lifestyle_banner',
      overlay: 'minimal',
      ticker_style: 'modern',
      icon: '✨',
    },
  }
}
