/**
 * Refresh public/videos.json.
 * PRIMARY: accumulates verified publications from ALL durable sources:
 *   1. PublicationLedger — output/data (per-run scratch) + data/ (cache-persisted)
 *   2. production/runs/{jobDir}/publication.json — committed verification evidence
 *   3. public/videos/{videoId}.json — committed gallery metadata enrichment
 * Merged and deduplicated by YouTube videoId. Prefers canonical local
 * thumbnails (public/thumbnails/{videoId}.png) generated by DISTRIBUTE.
 * FALLBACK: YouTube RSS feed (for pre-ledger videos).
 *
 * Invariant: if a video appears here, it has passed post-publish verification
 * (ledger 3-axis state OR committed production/runs verification).
 * Never regenerates thumbnails — consumes the canonical artifact.
 *
 * Usage: node scripts/update-videos.mjs
 */

import { writeFileSync, existsSync, mkdirSync, readFileSync, readdirSync } from 'node:fs'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(__dirname, '..', 'public', 'videos.json')
const THUMBS_DIR = resolve(__dirname, '..', 'public', 'thumbnails')
const DATA_DIR = resolve(__dirname, '..', 'data')
const LEDGER_PATH = resolve(DATA_DIR, 'publication-ledger.json')
// Production ledger written by composer.mjs (DISTRIBUTE/VERIFY stages)
const PROD_LEDGER_PATH = resolve(__dirname, '..', 'output', 'data', 'publication-ledger.json')
// Committed verification evidence — survives cache eviction
const RUNS_DIR = resolve(__dirname, '..', 'production', 'runs')
// Committed gallery metadata enrichment
const DETAIL_DIR = resolve(__dirname, '..', 'public', 'videos')
const CHANNEL_ID = process.env.YOUTUBE_CHANNEL_ID || 'UC4UC7z16EtqtI-TJzeGZKjQ'

const decodeHtml = (s = '') => s
  .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#39;/g, "'")

/** Resolve thumbnail — deterministic, no guessing.
 *  Prefer canonical local thumbnail (public/thumbnails/{videoId}.png),
 *  then explicit URL, then YouTube maxres fallback. */
function resolveThumbnailUrl(videoId, thumbnailField) {
  // 1. Canonical local thumbnail from DISTRIBUTE stage
  if (videoId && existsSync(resolve(THUMBS_DIR, `${videoId}.png`))) {
    return `/thumbnails/${videoId}.png`
  }
  // 2. Explicit URL from production verification
  if (typeof thumbnailField === 'string' && thumbnailField.startsWith('http')) return thumbnailField
  // 3. YouTube verified fallback — maxres first
  if (videoId) return `https://i.ytimg.com/vi/${videoId}/maxresdefault.jpg`
  // 4. Static placeholder
  return '/assets/placeholder-thumbnail.jpg'
}

/** Merge verified publication sources into a single videoId-keyed collection.
 *  Pure function (no I/O) so the accumulation contract is unit-testable.
 *
 *  Source precedence for duplicate videoIds:
 *  - ledger entries (richest: title/description/category/3-axis state) win
 *  - production/runs publications fill verification/publishedAt/thumbnail gaps
 *  - committed gallery detail pages enrich title/category/description only when
 *    the verified record still lacks them (never invents new videoIds)
 *
 *  @param {Object} opts
 *  @param {Array}  opts.ledgerEntries   PublicationLedger entry objects
 *  @param {Array}  opts.runPublications production/runs publication.json objects
 *  @param {Array}  opts.detailPages     public/videos/{videoId}.json objects
 *  @returns {Array} merged raw records (videoId-keyed, insertion-ordered)
 */
export function mergeVerifiedPublicationSources({ ledgerEntries = [], runPublications = [], detailPages = [] } = {}) {
  const byId = new Map()

  // 1. PublicationLedger — accepts uploadState SUCCESS + verificationState != REJECTED
  for (const e of ledgerEntries) {
    if (!e?.videoId || e.uploadState !== 'SUCCESS' || e.verificationState === 'REJECTED') continue
    byId.set(e.videoId, { ...byId.get(e.videoId), ...e })
  }

  // 2. production/runs evidence — upload.state SUCCESS + verification.passed true
  for (const d of runPublications) {
    if (!d?.videoId || d.upload?.state !== 'SUCCESS' || d.verification?.passed !== true) continue
    const cur = byId.get(d.videoId) || {}
    byId.set(d.videoId, {
      ...cur,
      videoId: d.videoId,
      publishedAt: cur.publishedAt || d.publishedAt || null,
      youtubeUrl: cur.youtubeUrl || d.distribution?.youtube?.url || `https://youtu.be/${d.videoId}`,
      thumbnail: cur.thumbnail || d.thumbnail?.remote?.url || null,
      thumbnailSha256: cur.thumbnailSha256 || d.thumbnail?.source?.sha256 || d.distribution?.youtube?.thumbnail?.sha256 || null,
      thumbnailWidth: cur.thumbnailWidth ?? d.thumbnail?.source?.width ?? null,
      thumbnailHeight: cur.thumbnailHeight ?? d.thumbnail?.source?.height ?? null,
      thumbnailAspectRatio: cur.thumbnailAspectRatio ?? d.thumbnail?.source?.aspectRatio ?? null,
      uploadState: 'SUCCESS',
      verificationState: cur.verificationState || d.verification?.state || 'PENDING',
      checks: cur.checks || {},
      distribution: cur.distribution || d.distribution || {},
    })
  }

  // 3. Committed gallery metadata — enrichment only (never fabricates videoIds)
  for (const d of detailPages) {
    const id = d?.videoId || d?.id
    if (!id || !byId.has(id)) continue
    const cur = byId.get(id)
    if (!cur.title) cur.title = d.title || null
    if (!cur.description) cur.description = d.description || null
    if (!cur.category) cur.category = d.category || null
    if (!cur.publishedAt) cur.publishedAt = d.publishedAt || null
  }

  return [...byId.values()]
}

/** Read verified videos from PublicationLedger + production/runs — 3-axis state model.
 *  Accumulates: per-run scratch ledger (output/data), cache-persisted ledger (data/),
 *  committed production/runs evidence, and committed gallery metadata enrichment. */
function readAccumulatedPublications() {
  // 1. Ledgers — output/data first (newest per-run), then data/ (accumulated superset)
  const ledgerEntries = []
  for (const path of [PROD_LEDGER_PATH, LEDGER_PATH]) {
    try {
      if (!existsSync(path)) continue
      const data = JSON.parse(readFileSync(path, 'utf-8'))
      ledgerEntries.push(...(data.entries || []))
    } catch {
      // skip corrupt ledger; continue to next source
    }
  }

  // 2. Committed production/runs evidence
  const runPublications = []
  try {
    for (const runDir of readdirSync(RUNS_DIR)) {
      const p = join(RUNS_DIR, runDir, 'publication.json')
      if (!existsSync(p)) continue
      try {
        runPublications.push(JSON.parse(readFileSync(p, 'utf-8')))
      } catch {
        // skip corrupt run record; continue
      }
    }
  } catch {
    // no production/runs directory (fresh repo)
  }

  // 3. Committed gallery metadata enrichment
  const detailPages = []
  try {
    for (const name of readdirSync(DETAIL_DIR)) {
      if (!name.endsWith('.json')) continue
      try {
        detailPages.push(JSON.parse(readFileSync(join(DETAIL_DIR, name), 'utf-8')))
      } catch {
        // skip corrupt detail page; continue
      }
    }
  } catch {
    // no detail pages
  }

  return mergeVerifiedPublicationSources({ ledgerEntries, runPublications, detailPages })
}

/** Map a merged verification record to the public videos.json schema.
 *  Deterministic; preserves 3-axis state and distribution. */
function toVideoEntry(e) {
  return {
    id: e.videoId,
    title: e.title || `Video ${e.videoId}`,
    description: e.description || e.title || '',
    category: e.category || 'general',
    publishedAt: e.publishedAt || e.verifiedAt || null,
    publishedLabel: e.publishedAt || e.verifiedAt
      ? new Date(e.publishedAt || e.verifiedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
      : '',
    thumbnail: resolveThumbnailUrl(e.videoId, e.thumbnail),
    thumbnailSha256: e.thumbnailSha256 || e.distribution?.youtube?.thumbnail?.sha256 || null,
    thumbnailWidth: e.thumbnailWidth || e.distribution?.youtube?.thumbnail?.width || null,
    thumbnailHeight: e.thumbnailHeight || e.distribution?.youtube?.thumbnail?.height || null,
    thumbnailAspectRatio: e.thumbnailAspectRatio || e.distribution?.youtube?.thumbnail?.aspectRatio || null,
    youtubeUrl: e.youtubeUrl || e.distribution?.youtube?.url || (e.videoId ? `https://youtu.be/${e.videoId}` : null),
    verified: e.verificationState === 'VERIFIED' || e.verificationState?.startsWith('VERIFIED'),
    verificationState: e.verificationState || 'PENDING',
    thumbnailState: e.thumbnailState || 'UNKNOWN',
    distribution: e.distribution || {},
  }
}

/** Fallback: YouTube RSS feed */
async function readRssFeed(channelId) {
  let xml
  let lastErr
  for (let attempt = 1; attempt <= 4; attempt++) {
    try {
      const feed = await fetch(`https://www.youtube.com/feeds/videos.xml?channel_id=${channelId}`, {
        headers: { 'user-agent': 'Mozilla/5.0 (compatible; NEWS-MONSTER/1.0)' },
        signal: AbortSignal.timeout(8000),
      })
      if (feed.ok) { xml = await feed.text(); break }
      lastErr = new Error(`feed unavailable: ${feed.status}`)
    } catch (e) { lastErr = e }
    await new Promise(r => setTimeout(r, attempt * 1200))
  }
  if (!xml) {
    console.warn(`⚠️  RSS feed unavailable: ${lastErr?.message}`)
    return []
  }
  const entries = [...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)]
  return entries.map(m => {
    const e = m[1] || ''
    const id = /yt:video:([A-Za-z0-9_-]+)/.exec(e)?.[1] || null
    const title = decodeHtml(/<title>([\s\S]*?)<\/title>/.exec(e)?.[1] || '')
    const published = /<published>([\s\S]*?)<\/published>/.exec(e)?.[1] || null
    return {
      id, title,
      publishedAt: published || null,
      publishedLabel: published
        ? new Date(published).toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
        : '',
      thumbnail: resolveThumbnailUrl(id, null),
      thumbnailSha256: null,
      thumbnailWidth: null,
      thumbnailHeight: null,
      thumbnailAspectRatio: null,
      verified: false,
      verificationState: 'RSS_FALLBACK',
      thumbnailState: 'UNKNOWN',
    }
  }).filter(v => v.id)
}

export async function refreshVideosFeed(channelId = CHANNEL_ID) {
  // Primary: accumulated verified publications (ledger + production/runs + detail pages)
  const rawEntries = readAccumulatedPublications()
  const verifiedVideos = rawEntries
    .filter(e => e.uploadState === 'SUCCESS' && e.verificationState !== 'REJECTED')
    .map(toVideoEntry)

  // Deterministic: newest published first
  verifiedVideos.sort((a, b) => new Date(b.publishedAt || 0) - new Date(a.publishedAt || 0))

  if (verifiedVideos.length > 0) {
    const json = { channelId, updatedAt: new Date().toISOString(), source: 'production-ledger', videos: verifiedVideos }
    if (!existsSync(dirname(OUT))) mkdirSync(dirname(OUT), { recursive: true })
    writeFileSync(OUT, JSON.stringify(json, null, 2))
    console.log(`📋 videos.json from accumulated verified publications: ${verifiedVideos.length} videos → ${OUT}`)
    return json
  }

  // Fallback: YouTube RSS (for pre-ledger videos)
  console.log('📋 no verified publications — falling back to YouTube RSS feed')
  const rssVideos = await readRssFeed(channelId)
  if (rssVideos.length === 0) {
    console.warn('⚠️  videos.json refresh skipped — no data available')
    return null
  }
  const json = { channelId, updatedAt: new Date().toISOString(), source: 'youtube-rss', videos: rssVideos }
  if (!existsSync(dirname(OUT))) mkdirSync(dirname(OUT), { recursive: true })
  writeFileSync(OUT, JSON.stringify(json, null, 2))
  console.log(`📋 videos.json from RSS: ${rssVideos.length} videos → ${OUT}`)
  return json
}

// CLI entry only — do not run the refresh when imported by tests/modules.
import { pathToFileURL } from 'node:url'
const isMain = process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href
if (isMain) {
  refreshVideosFeed().catch(e => {
    console.error(`❌ videos.json refresh failed: ${e.message}`)
    process.exit(1)
  })
}