/**
 * Refresh public/videos.json.
 * PRIMARY: reads from PublicationLedger (verified publications only),
 *   preferring canonical local thumbnails (public/thumbnails/{videoId}.png)
 *   generated by the DISTRIBUTE stage.
 * FALLBACK: YouTube RSS feed (for pre-ledger videos).
 *
 * Invariant: if a video appears here, it has passed post-publish verification.
 * Never regenerates thumbnails — consumes the canonical artifact.
 *
 * Usage: node scripts/update-videos.mjs
 */

import { writeFileSync, existsSync, mkdirSync, readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(__dirname, '..', 'public', 'videos.json')
const THUMBS_DIR = resolve(__dirname, '..', 'public', 'thumbnails')
const DATA_DIR = resolve(__dirname, '..', 'data')
const LEDGER_PATH = resolve(DATA_DIR, 'publication-ledger.json')
// Production ledger written by composer.mjs (DISTRIBUTE/VERIFY stages)
const PROD_LEDGER_PATH = resolve(__dirname, '..', 'output', 'data', 'publication-ledger.json')
const CHANNEL_ID = process.env.YOUTUBE_CHANNEL_ID || 'UC4UC7z16EtqtI-TJzeGZKjQ'

const decodeHtml = (s = '') => s
  .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#39;/g, "'")

/** Resolve thumbnail — deterministic, no guessing.
 *  Prefer canonical local thumbnail (public/thumbnails/{videoId}.png),
 *  then explicit URL, then YouTube maxres fallback. */
function resolveThumbnailUrl(videoId, thumbnailField) {
  // 1. Canonical local thumbnail from DISTRIBUTE stage
  if (videoId && existsSync(resolve(THUMBS_DIR, `${videoId}.png`))) {
    return `/thumbnails/${videoId}.png`
  }
  // 2. Explicit URL from production verification
  if (typeof thumbnailField === 'string' && thumbnailField.startsWith('http')) return thumbnailField
  // 3. YouTube verified fallback — maxres first
  if (videoId) return `https://i.ytimg.com/vi/${videoId}/maxresdefault.jpg`
  // 4. Static placeholder
  return '/assets/placeholder-thumbnail.jpg'
}

/** Read verified videos from PublicationLedger — uses 3-axis state model.
 *  Checks production ledger first (output/data), then top-level data/. */
function readLedger() {
  const candidates = [PROD_LEDGER_PATH, LEDGER_PATH]
  for (const path of candidates) {
    try {
      if (!existsSync(path)) continue
      const data = JSON.parse(readFileSync(path, 'utf-8'))
      const entries = (data.entries || []).reverse()
        .filter(e => e.uploadState === 'SUCCESS' && e.verificationState !== 'REJECTED')
        .map(e => ({
          id: e.videoId,
          title: e.title || `Video ${e.videoId}`,
          category: e.category || 'general',
          publishedAt: e.publishedAt || e.verifiedAt,
          publishedLabel: e.publishedAt
            ? new Date(e.publishedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
            : '',
          thumbnail: resolveThumbnailUrl(e.videoId, e.thumbnail),
          youtubeUrl: e.youtubeUrl || null,
          verified: e.verificationState === 'VERIFIED',
          verificationState: e.verificationState || 'PENDING',
          thumbnailState: e.thumbnailState || 'UNKNOWN',
          distribution: e.distribution || {},
        }))
      if (entries.length > 0) return { entries, source: path === PROD_LEDGER_PATH ? 'production-ledger' : 'publication-ledger' }
    } catch {
      // try next candidate
    }
  }
  return { entries: [], source: null }
}

/** Fallback: YouTube RSS feed */
async function readRssFeed(channelId) {
  let xml
  let lastErr
  for (let attempt = 1; attempt <= 4; attempt++) {
    try {
      const feed = await fetch(`https://www.youtube.com/feeds/videos.xml?channel_id=${channelId}`, {
        headers: { 'user-agent': 'Mozilla/5.0 (compatible; NEWS-MONSTER/1.0)' },
        signal: AbortSignal.timeout(8000),
      })
      if (feed.ok) { xml = await feed.text(); break }
      lastErr = new Error(`feed unavailable: ${feed.status}`)
    } catch (e) { lastErr = e }
    await new Promise(r => setTimeout(r, attempt * 1200))
  }
  if (!xml) {
    console.warn(`⚠️  RSS feed unavailable: ${lastErr?.message}`)
    return []
  }
  const entries = [...xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)]
  return entries.map(m => {
    const e = m[1] || ''
    const id = /yt:video:([A-Za-z0-9_-]+)/.exec(e)?.[1] || null
    const title = decodeHtml(/<title>([\s\S]*?)<\/title>/.exec(e)?.[1] || '')
    const published = /<published>([\s\S]*?)<\/published>/.exec(e)?.[1] || null
    return {
      id, title,
      publishedAt: published || null,
      publishedLabel: published
        ? new Date(published).toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
        : '',
      thumbnail: resolveThumbnailUrl(id, null),
      verified: false,
      verificationState: 'RSS_FALLBACK',
      thumbnailState: 'UNKNOWN',
    }
  }).filter(v => v.id)
}

export async function refreshVideosFeed(channelId = CHANNEL_ID) {
  // Primary: PublicationLedger (verified publications), prefer canonical local thumbnails
  const { entries: ledgerVideos, source } = readLedger()
  if (ledgerVideos.length > 0) {
    const json = { channelId, updatedAt: new Date().toISOString(), source, videos: ledgerVideos }
    if (!existsSync(dirname(OUT))) mkdirSync(dirname(OUT), { recursive: true })
    writeFileSync(OUT, JSON.stringify(json, null, 2))
    console.log(`📋 videos.json from ${source}: ${ledgerVideos.length} verified videos → ${OUT}`)
    return json
  }

  // Fallback: YouTube RSS (for pre-ledger videos)
  console.log('📋 no ledger entries — falling back to YouTube RSS feed')
  const rssVideos = await readRssFeed(channelId)
  if (rssVideos.length === 0) {
    console.warn('⚠️  videos.json refresh skipped — no data available')
    return null
  }
  const json = { channelId, updatedAt: new Date().toISOString(), source: 'youtube-rss', videos: rssVideos }
  if (!existsSync(dirname(OUT))) mkdirSync(dirname(OUT), { recursive: true })
  writeFileSync(OUT, JSON.stringify(json, null, 2))
  console.log(`📋 videos.json from RSS: ${rssVideos.length} videos → ${OUT}`)
  return json
}

if (import.meta.url.endsWith('update-videos.mjs')) {
  refreshVideosFeed().catch(e => {
    console.error(`❌ videos.json refresh failed: ${e.message}`)
    process.exit(1)
  })
}
